name: Deploy Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v6.0.2 direct commit hash
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        # v6.0.0
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
        # v2.9.1
      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal
      - name: Restore Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
      - name: Build
        run: cargo build --verbose
      - name: Run
        run: cargo run --verbose
        # v5.0.0
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: public/
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy artifact to pages
        id: deployment
        # v5 direct commit hash
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128

